### ISSUE TITLE
Make proposer set manage pages (client side)

### ISSUE THREAD

**Issue by stompesi** [radiusxyz/proposer-set-manager#1]
## What is a function?

> Please write a description of the function that the requested feature is trying to solve.

Rollups require UI and functions that create a proposer set, and a sequencer to join that proposer set.

## Todo

> Write down a description of why we need this feature.

Each page and function needs to be designed 

- [ ] Generate proposer set 
- [ ] Get proposer set list
  - Filter function
- [ ] Get proposer set (detail page)
- [ ] Join proposer set
- [ ] Leave proposer set

## Reference (optional)
