### ISSUE TITLE
Basic server functions

### ISSUE THREAD

**Issue by stompesi** [radiusxyz/proposer-set-manager#3]
## What is a function?

> Please write a description of the function that the requested feature is trying to solve.

To show the client the information in the proposer set, we need to update the database by getting the information from a rollup(blockchain). We also need to develop an API to provide the proposer set's information to the client.

## Todo

> Write down a description of why we need this feature.

- [ ] Add event listener (for getting proposer set information from a rollup)
- [ ] Store data
- [ ] Load data
- [ ] REST API
  - [ ] Get proposer set list
  - [ ] Get proposer set
